GET http://localhost:3000/courses

###
GET http://localhost:3000/courses?search=React

###
GET http://localhost:3000/courses?orderBy=title

###
GET http://localhost:3000/courses?orderBy=title&page=4

###
POST http://localhost:3000/courses
Content-Type: application/json

{
    "title": "course C#",
    "description": "description C#"
}

###
PUT http://localhost:3000/courses/2
Content-Type: application/json

{
    "name": "course3"
}

###
GET http://localhost:3000/courses/1743467e-b7ac-4902-8050-963425e72177
